stages:
  - build

variables:

  #STAGE
  ACCOUNT_ID_INFRA_STAGE: 121827225315
  AWS_REGION_INFRA_STAGE: "us-west-2"


#blox-infra-stage
Build stage Docker image:
  stage: build
  tags:
    - blox-infra-stage
  script:
    - docker build -t test-build -f Dockerfile .

  only:
    - main
