stages:
  - build

variables:

  #STAGE
  ACCOUNT_ID_INFRA_STAGE: 121827225315
  AWS_REGION_INFRA_STAGE: "us-west-2"


#blox-infra-stage
Build stage Docker image:
  stage: build
  tags:
    - blox-infra-stage
  script:
    - export S3_BUCKET=$S3_BUCKET
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - docker build -t test-build -f Dockerfile .

  only:
    - main
